### ISSUE TITLE
I see this error. :(

### ISSUE THREAD

**Issue by guadacredhot** [ShadowHackrs/instagram-autoreport#2]
Enter the number of reports you want to send: 10

Traceback (most recent call last):
  File "/home/kaliuser/.local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaliuser/igbrute/instagram-autoreport/insta.py", line 42, in <module>
    driver = webdriver.Chrome(options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kaliuser/.local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/kaliuser/.local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/home/kaliuser/.local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

**Comment by ShadowHackrs** [comment]
u need install this version

https://chromedriver.storage.googleapis.com/index.html?path=114.0.5735.16%2F

**Comment by guadacredhot** [comment]
Thanks for your answer, I believe my problem is that I am running the code in kali linux. Do I need Windows to do it?
